version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - default
  crawler:
    build:
      context: ./bot
      dockerfile: ../docker/crawler.Dockerfile
    networks:
      - default
