version: "3"

services:
  web:
    build:
      context: ./src
      dockerfile: ../docker/web.Dockerfile
    networks:
      - default
  crawler:
    build:
      context: ./bot
      dockerfile: ../docker/crawler.Dockerfile
    networks:
      - default
