version: "3"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/web.Dockerfile
        ports:
            - "0.0.0.0:${PORT:-80}:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - default
    crawler:
        build:
            context: ./bot
            dockerfile: ../docker/crawler.Dockerfile
        environment:
            - CHROMIUM_PLATFORM=${CHROMIUM_PLATFORM:-amd64}
        networks:
            - default
